set -g status-right "%d %b %R "
set -g status-right-style "fg=white"
set -g status-left ""

set -g status-justify absolute-centre
set -g status-style "bg=default"

set -g window-status-format "  #W  "
set -g window-status-style "bg=default fg=colour244"

set -g window-status-separator "#[fg=colour244] • "

set -g window-status-current-format "  #[bold]#W#[normal] #[fg=blue]󰊓#[fg=default] "
set -g window-status-current-style "bg=default fg=colour255"
